---
trigger:
- features/*

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:
    - task: AzureKeyVault@1
      displayName: 'Azure Key Vault: deloitte-key-vault'
      inputs:
        azureSubscription: 'Recipe_Azure_Service_Conn'
        KeyVaultName: 'deloitte-key-vault' 

    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Use Terraform 0.12.20'
      inputs:
        terraformVersion: 0.12.20

    - script: |
        terraform init -backend-config=storage_account_name=samstorageacc -backend-config=container_name=aws-load-balancer-with-provisioner -backend-config=key=AWSILB-Recipe.tfstate -backend-config=resource_group_name=AZRG-USE-ITS-RCPNPD-NPD-001 -backend-config=subscription_id=$(subscription-id) -backend-config=tenant_id=$(tenant-id) -backend-config=client_id=$(client-id) -backend-config=client_secret=$(client-secret)
      displayName: terraform init 
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'