trigger:
- master
pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 'terraform-webfront-aws-HCL'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: deloitte-key-vault'
  inputs:
    azureSubscription: 'Recipe_Azure_Service_Conn'
    KeyVaultName: 'deloitte-key-vault'

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform 0.12.20'
  inputs:
    terraformVersion: 0.12.20

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform init'
  inputs:
    command: init
    terraformVersion: 0.12.20
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'
    backendType: azurerm
    backendServiceArm: 'Recipe_Azure_Service_Conn'
    backendAzureRmResourceGroupName: 'AZRG-USE-ITS-RCPNPD-NPD-001'
    backendAzureRmStorageAccountName: samstorageacc
    backendAzureRmContainerName: 'aws-load-balancer-with-provisioner'
    backendAzureRmKey: 'AWSILB-Recipe.tfstate'

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform validate'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: 'terraform plan'
  inputs:
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'
    environmentServiceName: 'Recipe_Azure_Service_Conn'
    secureVarsFile: 'awslb_yamltest.tfvars.json'
    commandOptions: '-var client_id=$(client-id) -var client_secret=$(client-secret) -var access_key=$(access-key) -var secret_key=$(secret-key)'
