---
trigger:
- features/*
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BUILD
  jobs:
  - job: Test
    steps:
    - script: |
        terraform validate 
      displayName: terraform validate 
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifact: webfront-build

