---
trigger:
- features/*

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

stages:
- stage: BUILD
  jobs:
  - job: Build
    steps:
    - task: AzureKeyVault@1
      displayName: 'Azure Key Vault: deloitte-key-vault'
      inputs:
        azureSubscription: 'Recipe_Azure_Service_Conn'
        KeyVaultName: 'deloitte-key-vault' 

    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Use Terraform 0.12.20'
      inputs:
        terraformVersion: 0.12.20

    - script: |
        terraform init container_name='aws-load-balancer-with-provisioner'
      displayName: terraform init
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-webfront-aws-HCL'